### ISSUE TITLE
table-select

### ISSUE THREAD

**Issue by snowerskk** [cabinet-fe/element-ultra#36]
**描述你的需求**
点击按钮弹出选择弹框，选择弹框内表格的数据，将选中数据展示在页面中的表格内

**补充说明**
原生表格
<tr>
<td>
  <el-checkbox @change="" value="a"></el-checkbox></td>
</tr>

按钮
表格

el-radio

modelValue: []

v-model
columns
multiple
api 
pagination 和 api配合使用
data 优先级高一点

插槽
seacher

**Comment by wenhongjie** [comment]
@snowerskk 
代码优化：
```ts
 // inject('someKey')

// 优化至
// 文件token.ts
const someKey: InjectionKey<Type> = Symbol('someKey')

import { someKey } from './token'
inject(someKey)
```

**Comment by wenhongjie** [comment]
@snowerskk 
一下文件命名的含义是啥啊
- dialog-cl
- table-cl

**Comment by snowerskk** [comment]
基本功能完成
