### ISSUE TITLE
el-multiple-form 组件需要增加合计功能

### ISSUE THREAD

**Issue by fdf-hash** [cabinet-fe/element-ultra#64]
**改进的需求**
![)54 `(6E$MKE8EUTCD1276M](https://user-images.githubusercontent.com/58969488/203209606-43dd3853-3b5f-49a8-a489-a6fa86675d44.png)

[**备注**]

**Comment by wenhongjie** [comment]
已完成 @fdf-hash 
这个应该是一个新功能

**Comment by wenhongjie** [comment]
@fdf-hash 

在要合计的列配置上加一个summary属性， 可以属布尔值和函数
```
const columns = [
  {
    name: '数量',
    key: 'count',
    summary: total => total + '元'
  }
]
```

**Comment by fdf-hash** [comment]
@wenhongjie 需要根据字段align 位置居中、靠左、靠右。
